### ISSUE TITLE
Is it possible to add a link field in the Google Search Results Scraper, and the value of link is the value of url? Because the url is not clickable in rss reader.

### ISSUE THREAD

**Issue by Markcco** [apify-projects/store-google-search-scraper#120] opened 2022-06-21 09:34 UTC
Is it possible to add a link field in the Google Search Results Scraper, and the value of link is the value of url? Because the url is not clickable in rss reader.

**Comment by metalwarrior665** [comment] 2023-01-12 14:58
Duplicate of https://github.com/apify-projects/store-google-search-scraper/issues/119

**Closed by metalwarrior665** 2023-01-12 14:58 UTC
